### PR TITLE
fix regex for settings

### PR DESCRIPTION
**Pull request by mwrock**
chef pipeline still broken:
```
         1) 1.3 validate output File "C:/Users/Administrator/.acceptance/configure-a-resource/1.3.1/stdout" content should match /\s{4}\+\+\+ C:\\Users\\Administrator\\chef-repo\/settings.ini/
            Failure/Error: its(:content) { should match matcher }
       
       [2016-02-19T02:21:40+00:00] WARN: No cookbooks directory found at or above current directory.  Assuming C:/Users/Administrator/chef-repo.Starting Chef Client, version 12.8.0resolving cookbooks for run list: []Synchronizing Cookbooks:Compiling Cookbooks...[2016-02-19T02:22:16+00:00] WARN: Node WIN-G5EC6HAR3D7 has an empty run list.Converging 1 resourcesRecipe: @recipe_files::C:/Users/Administrator/chef-repo/hello.rb  * file[C:\\Users\\Administrator\\chef-repo\\settings.ini] action create    - create new file C:\\Users\\Administrator\\chef-repo\\settings.ini    - update content in file C:\\Users\\Administrator\\chef-repo\\settings.ini from none to 6823fa    --- C:\\Users\\Administrator\\chef-repo\\settings.ini\t2016-02-19 02:22:16.000000000 +0000    +++ C:\\Users\\Administrator\\chef-repo/chef-settings.ini20160219-4092-1povl6b\t2016-02-19 02:22:16.000000000 +0000    @@ -1 +1,2 @@    +greeting=hello worldRunning handlers:Running handlers completeChef Client finished, 1/1 resources updated in 35 seconds" to match /\s{4}\+\+\+ C:\\Users\\Administrator\\chef-repo\/settings.ini/
       Diff:
       @@ -1,2 +1,21 @@
       -/\s{4}\+\+\+ C:\\Users\\Administrator\\chef-repo\/settings.ini/
       +[2016-02-19T02:21:40+00:00] WARN: No config file found or specified on command line, using command line options.
       +[2016-02-19T02:21:40+00:00] WARN: No cookbooks directory found at or above current directory.  Assuming C:/Users/Administrator/chef-repo.
       +Starting Chef Client, version 12.8.0
       +resolving cookbooks for run list: []
       +Synchronizing Cookbooks:
       +Compiling Cookbooks...
       +[2016-02-19T02:22:16+00:00] WARN: Node WIN-G5EC6HAR3D7 has an empty run list.
       +Converging 1 resources
       +Recipe: @recipe_files::C:/Users/Administrator/chef-repo/hello.rb
       +  * file[C:\Users\Administrator\chef-repo\settings.ini] action create
       +    - create new file C:\Users\Administrator\chef-repo\settings.ini
       +    - update content in file C:\Users\Administrator\chef-repo\settings.ini from none to 6823fa
       +    --- C:\Users\Administrator\chef-repo\settings.ini	2016-02-19 02:22:16.000000000 +0000
       +    +++ C:\Users\Administrator\chef-repo/chef-settings.ini20160219-4092-1povl6b	2016-02-19 02:22:16.000000000 +0000
       +    @@ -1 +1,2 @@
       +    +greeting=hello world
       +
       +Running handlers:
       +Running handlers complete
       +Chef Client finished, 1/1 resources updated in 35 seconds
            # C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/learn-the-basics-windows/recipes/lesson1.rb:88:in `block (5 levels) in from_file'
       
       Finished in 7.73 seconds (files took 1.72 seconds to load)
       43 examples, 1 failure
```

### CODE REVIEW

**Comment by btm** [comment]
@tpetchel it seems likely this change was caused by https://github.com/chef/chef/pull/4582, and we should confirm with @thommay that this is intended behavior.

**Comment by thommay** [comment]
@btm i don't really understand why it would be, unless the file that's being checked is a temporary file, in which case why are we checking it?

**Comment by tpetchel** [comment]
@btm: Thanks for the background. Was more of a curiosity than anything else.

**Comment by btm** [comment]
This was because of https://github.com/chef/chef/pull/4582. This test ensures the output of chef-client doesn't change and will break if it does. When the file provider changes a file it shows a diff between the existing file and the tempfile, and that diff shows both filenames. The matchers in the test hide that they're checking the real file name and the temp file name because they only match part of the line and ignore the timestamp looking data added to the tempfilename, as well as the times that show up like:


```
    - update content in file C:\Users\Administrator\chef-repo\settings.ini from none to 6823fa
    --- C:\Users\Administrator\chef-repo\settings.ini   2016-02-19 02:22:16.000000000 +0000
    +++ C:\Users\Administrator\chef-repo/chef-settings.ini20160219-4092-1povl6b 2016-02-19 02:22:16.000000000 +0000
```

The third line did change since we started putting 'chef-' in front of tempfiles.

**Pull request merged**
